"""
This file extracts the data from the xml file generated by API.py in a json format.
Here the link only store the pdf link of the paper to avoid confusion.
And the author tag only stores the list of names of the authors.
"""


import xml.etree.ElementTree as ET
tree = ET.parse('temp')
root = tree.getroot()
data={}



for child in root:
    childTag=child.tag.split('}')[1]
    if childTag=='entry':
        for childChild in child:
            childChildTag = childChild.tag.split('}')[1]

            if childChildTag=='author':
                if 'author' not in data:
                    data['author']=[]
                data['author'].append(childChild[0].text)
            elif childChildTag=='link':
                if 'title' in childChild.attrib and childChild.attrib['title']=='pdf':
                    data['link']=childChild.attrib['href']
            else:
                data[childChildTag]=childChild.text
            
print(data)